### ISSUE TITLE
Travis-ci Build Fail 

### ISSUE THREAD

**Issue by jdubchak** [UBC-MDS/hamr#24]
The build failed for this reason: 

### ** Examples
> 
> compare_model(data.frame(ex = c(1, 2, 3), bf = c(6, 8, "")), "bf", "DIP", "")
Error in method %in% c("CC", "MIP", "DIP") : object 'method' not found
Calls: compare_model -> %in%
Execution halted
R CMD check failed

**Comment by yllz** [comment]
efcb874e03b41ccbb4f3d951ccdcd58208561e48
